# https://github.com/googleapis/googleapis/blob/master/google/api/service.proto
type: google.api.Service
config_version: 3

name: bookstore.endpoints.experimental-229809.cloud.goog

title: Bookstore gRPC API
apis:
  - name: endpoints.examples.bookstore.Bookstore

usage:
  rules:
    - selector: "*"
      allow_unregistered_calls: false
