apiVersion: v1
kind: Service
metadata:
  name: esp-grpc-bookstore
spec:
  type: LoadBalancer
  selector:
    app: esp-grpc-bookstore
  ports:
    - name: esp
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: esp2
      protocol: TCP
      port: 9001
      targetPort: 9001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esp-grpc-bookstore
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: esp-grpc-bookstore
  template:
    metadata:
      labels:
        app: esp-grpc-bookstore
    spec:
      containers:
        - name: esp
          image: gcr.io/endpoints-release/endpoints-runtime:1
          args: [
            "--http2_port=9000",
            "--status_port=8090",
            "--service=bookstore.endpoints.experimental-229809.cloud.goog",
            "--rollout_strategy=managed",
            "--backend=grpc://127.0.0.1:8000",
            "--service_account_key=/etc/nginx/creds/gcloud-service-account.json"
          ]
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: gcloud-service-account
              mountPath: "/etc/nginx/creds"
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
              ephemeral-storage: 100Mi
            limits:
              memory: 100Mi
              ephemeral-storage: 100Mi
        - name: esp2
          image: gcr.io/endpoints-release/endpoints-runtime:1
          args: [
            "--http2_port=9001",
            "--status_port=8091",
            "--service=bookstore2.endpoints.experimental-229809.cloud.goog",
            "--rollout_strategy=managed",
            "--backend=grpc://127.0.0.1:8000",
            "--service_account_key=/etc/nginx/creds/gcloud-service-account.json"
          ]
          ports:
            - containerPort: 9001
          volumeMounts:
            - name: gcloud-service-account
              mountPath: "/etc/nginx/creds"
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
              ephemeral-storage: 100Mi
            limits:
              memory: 100Mi
              ephemeral-storage: 100Mi
        - name: bookstore
          # https://github.com/GoogleCloudPlatform/python-docs-samples/tree/main/endpoints/bookstore-grpc
          image: gcr.io/endpointsv2/python-grpc-bookstore-server:1
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
              ephemeral-storage: 100Mi
            limits:
              memory: 100Mi
              ephemeral-storage: 100Mi

      volumes:
        - name: gcloud-service-account
          secret:
            secretName: gcloud-service-account
            items:
              - key: "experimental-general"
                path: 'gcloud-service-account.json'
